### ISSUE TITLE
Custom Chart CLI

### ISSUE THREAD

**Issue by JackTR77** [WerlingM/alerts_user_guide#1]
Sorry to disturb you. May I get your help on how to create chart using the command. Currently I stuck at this part. I not sure where to put the file at. Can you guide me on how to do at this steps please.
![image](https://user-images.githubusercontent.com/51741408/59339593-0817b580-8d37-11e9-8432-2a51932844e1.png)
The sample file I used I the Chords Chart uploaded by you.

**Comment by WerlingM** [comment]
From what I recall the `chartname.js` argument is the name you want the chart to have on the Zoomdata server.  The `<path>` is the path to the chart Javascript source code file on your local machine.  The command uploads the file to the Zoomdata server, so you don't have to specify any server side paths.

I'm no longer supporting the Zoomdata projects, so if you have more questions you're best bet is to reach out to Zoomdata customer support.
